export default [
  {
    author: 'Admin',
    title: 'The best games of 2021',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'best',
    headimg_dir: '8fef279b-4331-4b70-adbd-0a9f2d00dbe0',
  },
  {
    author: 'Admin',
    title: 'How the open world is being finalized',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'beatiful',
    headimg_dir: '18b56300-3b30-425e-854a-8b580508d329',
  },
  {
    author: 'Admin',
    title: 'Review on Gadgets for Gamers',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'software',
    headimg_dir: '42fa6cc1-92c8-426b-93ff-b502df5b8a53',
  },
  {
    author: 'Admin',
    title: 'Enjoy learning the game in 1 evening',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'beatiful',
    headimg_dir: '59fd591a-09cf-4d19-9aef-6a7b2c12478a',
  },
  {
    author: 'Admin',
    title: 'Games that you will want to play again',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'beatiful',
    headimg_dir: '592db5c1-f5c1-4268-97de-32684c93241f',
  },
  {
    author: 'Admin',
    title: '10 Amazing new games',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'best',
    headimg_dir: '2067d931-bd87-48f7-8ad9-79124e41c2c4',
  },
  {
    author: 'Admin',
    title: 'Creativity based on your adventures',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'another',
    headimg_dir: '2527ae0c-1d82-47ab-9bf6-f6ee3465f2b1',
  },
  {
    author: 'Admin',
    title: 'Disadvantages of hardware for games',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'software',
    headimg_dir: '5873f73d-2dda-4bc2-86b9-f8c1735f5167',
  },
  {
    author: 'Admin',
    title: 'Drive games for any player',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'singles',
    headimg_dir: '58291574-f011-4ca4-82ed-00b86907df76',
  },
  {
    author: 'Admin',
    title: 'Characters worth paying attention to',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'best',
    headimg_dir: 'a0eb2006-ee77-47bf-b2ee-97f34782ace4',
  },
  {
    author: 'Admin',
    title: 'Remembering the classics...',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'beatiful',
    headimg_dir: 'b25009d3-eaa7-423d-88ad-9d787b574f90',
  },
  {
    author: 'Admin',
    title: 'Figurines for fans of your favorite game',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'another',
    headimg_dir: 'd0b0ef70-226a-425f-8aa0-949d5341a4cf',
  },
  {
    author: 'Admin',
    title: 'The eternal software question',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'software',
    headimg_dir: 'd806c924-7735-4fdd-a56b-b5803a5cc299',
  },
  {
    author: 'Admin',
    title: 'Top 5 worlds to explore',
    h1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. Fusce urna quam, euismod sit amet mollis quis, vestibulum quis velit. Morbi id dictum quam, ut commodo lorem. In at nisi nec arcu porttitor aliquet vitae at dui.',
    content: 'This place for Markdown content',
    category: 'singles',
    headimg_dir: 'fc66817a-e943-478c-9f3c-cb1547bec922',
  },
];
